package com.example.dota2timer.ui.theme

import com.example.dota2timer.R

data class HeroInfo(
    val name: String,
    val iconResId: Int,
    val ultIconResId: Int,
    val timeModifiers: List<Int> // Временные модификаторы для героя
)

val heroesInfo = listOf(
    HeroInfo("Pick", R.drawable.ic_pick, R.drawable.ic_ult, listOf(60, 30, 10)),
//    HeroInfo("Axe", R.drawable.ic_axe, R.drawable.ic_ult_axe, listOf(60, 30, 10)),
//    HeroInfo("Enigma", R.drawable.ic_3, R.drawable.ic_ult_enigma, listOf(60, 30, 10)),
//    HeroInfo("Pudge", R.drawable.ic_pudge, R.drawable.ic_ult_pudge, listOf(100, 50, 20)),

    HeroInfo("Abaddon", R.drawable.ic_abaddon, R.drawable.ic_ult_abaddon, listOf(80, 70, 60)),
    HeroInfo("Alchemist", R.drawable.ic_alchemist, R.drawable.ic_ult_alchemist, listOf(60, 60, 60)),
    HeroInfo("Ancient Apparition", R.drawable.ic_ancient_apparition, R.drawable.ic_ult_ancient_apparition, listOf(60, 50, 40)),
    HeroInfo("Anti-Mage", R.drawable.ic_anti_mage, R.drawable.ic_ult_anti_mage, listOf(70, 70, 70)),
    HeroInfo("Arc Warden", R.drawable.ic_arc_warden, R.drawable.ic_ult_arc_warden, listOf(70, 60, 50)),
    HeroInfo("Axe", R.drawable.ic_axe, R.drawable.ic_ult_axe, listOf(100, 85, 70)),
    HeroInfo("Bane", R.drawable.ic_bane, R.drawable.ic_ult_bane, listOf(120, 110, 100)),
    HeroInfo("Batrider", R.drawable.ic_batrider, R.drawable.ic_ult_batrider, listOf(120, 115, 110)),
    HeroInfo("Beastmaster", R.drawable.ic_beastmaster, R.drawable.ic_ult_beastmaster, listOf(90, 75, 60)),
    HeroInfo("Bloodseeker", R.drawable.ic_bloodseeker, R.drawable.ic_ult_bloodseeker, listOf(70, 70, 70)),
    HeroInfo("Bounty Hunter", R.drawable.ic_bounty_hunter, R.drawable.ic_ult_bounty_hunter, listOf(6, 5, 4)),
    HeroInfo("Brewmaster", R.drawable.ic_brewmaster, R.drawable.ic_ult_brewmaster, listOf(140, 130, 120)),
    HeroInfo("Bristleback", R.drawable.ic_bristleback, R.drawable.ic_ult_bristleback, listOf(1, 1, 1)),
    HeroInfo("Broodmother", R.drawable.ic_broodmother, R.drawable.ic_ult_broodmother, listOf(9, 8, 7)),
//    HeroInfo("Centaur Warrunner", R.drawable.ic_centaur_warrunner, R.drawable.ic_ult_centaur_warrunner, listOf(140, 120, 100)),
//    HeroInfo("Chaos Knight", R.drawable.ic_chaos_knight, R.drawable.ic_ult_chaos_knight, listOf(80, 65, 45)),
//    HeroInfo("Chen", R.drawable.ic_chen, R.drawable.ic_ult_chen, listOf(150, 130, 110)),
//    HeroInfo("Clinkz", R.drawable.ic_clinkz, R.drawable.ic_ult_clinkz, listOf(100, 90, 80)),
//    HeroInfo("Clockwerk", R.drawable.ic_clockwerk, R.drawable.ic_ult_clockwerk, listOf(105, 95, 85)),
//    HeroInfo("Crystal Maiden", R.drawable.ic_crystal_maiden, R.drawable.ic_ult_crystal_maiden, listOf(130, 120, 110)),
//    HeroInfo("Dark Seer", R.drawable.ic_dark_seer, R.drawable.ic_ult_dark_seer, listOf(140, 120, 100)),
//    HeroInfo("Dazzle", R.drawable.ic_dazzle, R.drawable.ic_ult_dazzle, listOf(160, 140, 120)),
//    HeroInfo("Death Prophet", R.drawable.ic_death_prophet, R.drawable.ic_ult_death_prophet, listOf(120, 100, 90)),
//    HeroInfo("Disruptor", R.drawable.ic_disruptor, R.drawable.ic_ult_disruptor, listOf(130, 110, 90)),
//    HeroInfo("Doom", R.drawable.ic_doom, R.drawable.ic_ult_doom, listOf(145, 125, 105)),
//    HeroInfo("Dragon Knight", R.drawable.ic_dragon_knight, R.drawable.ic_ult_dragon_knight, listOf(160, 135, 110)),
//    HeroInfo("Drow Ranger", R.drawable.ic_drow_ranger, R.drawable.ic_ult_drow_ranger, listOf(100, 90, 80)),
//    HeroInfo("Earthshaker", R.drawable.ic_earthshaker, R.drawable.ic_ult_earthshaker, listOf(120, 110, 100)),
//    HeroInfo("Earth Spirit", R.drawable.ic_earth_spirit, R.drawable.ic_ult_earth_spirit, listOf(100, 90, 80)),
//    HeroInfo("Elder Titan", R.drawable.ic_elder_titan, R.drawable.ic_ult_elder_titan, listOf(170, 155, 140)),
//    HeroInfo("Ember Spirit", R.drawable.ic_ember_spirit, R.drawable.ic_ult_ember_spirit, listOf(120, 100, 80)),
//    HeroInfo("Enchantress", R.drawable.ic_enchantress, R.drawable.ic_ult_enchantress, listOf(140, 120, 100)),
//    HeroInfo("Enigma", R.drawable.ic_3, R.drawable.ic_ult_enigma, listOf(240, 210, 180)),
//    HeroInfo("Faceless Void", R.drawable.ic_faceless_void, R.drawable.ic_ult_faceless_void, listOf(160, 140, 120)),
//    HeroInfo("Grimstroke", R.drawable.ic_grimstroke, R.drawable.ic_ult_grimstroke, listOf(130, 110, 90)),
//    HeroInfo("Gyrocopter", R.drawable.ic_gyrocopter, R.drawable.ic_ult_gyrocopter, listOf(120, 100, 80)),
//    HeroInfo("Huskar", R.drawable.ic_huskar, R.drawable.ic_ult_huskar, listOf(85, 70, 55)),
//    HeroInfo("Invoker", R.drawable.ic_invoker, R.drawable.ic_ult_invoker, listOf(150, 130, 110)),
//    HeroInfo("Io", R.drawable.ic_io, R.drawable.ic_ult_io, listOf(180, 165, 150)),
//    HeroInfo("Jakiro", R.drawable.ic_jakiro, R.drawable.ic_ult_jakiro, listOf(140, 120, 100)),
//    HeroInfo("Juggernaut", R.drawable.ic_juggernaut, R.drawable.ic_ult_juggernaut, listOf(80, 70, 60)),
//    HeroInfo("Keeper of the Light", R.drawable.ic_keeper_of_the_light, R.drawable.ic_ult_keeper_of_the_light, listOf(130, 110, 90)),
//    HeroInfo("Kunkka", R.drawable.ic_kunkka, R.drawable.ic_ult_kunkka, listOf(100, 90, 80)),
//    HeroInfo("Legion Commander", R.drawable.ic_legion_commander, R.drawable.ic_ult_legion_commander, listOf(90, 80, 70)),
//    HeroInfo("Leshrac", R.drawable.ic_leshrac, R.drawable.ic_ult_leshrac, listOf(120, 100, 90)),
//    HeroInfo("Lich", R.drawable.ic_lich, R.drawable.ic_ult_lich, listOf(150, 130, 110)),
//    HeroInfo("Lina", R.drawable.ic_lina, R.drawable.ic_ult_lina, listOf(100, 90, 80)),
//    HeroInfo("Lion", R.drawable.ic_lion, R.drawable.ic_ult_lion, listOf(140, 120, 100)),
//    HeroInfo("Lone Druid", R.drawable.ic_lone_druid, R.drawable.ic_ult_lone_druid, listOf(150, 130, 110)),
//    HeroInfo("Luna", R.drawable.ic_luna, R.drawable.ic_ult_luna, listOf(100, 90, 80)),
//    HeroInfo("Lycan", R.drawable.ic_lycan, R.drawable.ic_ult_lycan, listOf(100, 90, 80)),
//    HeroInfo("Magnus", R.drawable.ic_magnus, R.drawable.ic_ult_magnus, listOf(140, 120, 100)),
//    HeroInfo("Mars", R.drawable.ic_mars, R.drawable.ic_ult_mars, listOf(100, 90, 80)),
//    HeroInfo("Medusa", R.drawable.ic_medusa, R.drawable.ic_ult_medusa, listOf(200, 175, 150)),
//    HeroInfo("Meepo", R.drawable.ic_meepo, R.drawable.ic_ult_meepo, listOf(160, 140, 120)),
//    HeroInfo("Mirana", R.drawable.ic_mirana, R.drawable.ic_ult_mirana, listOf(150, 130, 110)),
//    HeroInfo("Monkey King", R.drawable.ic_monkey_king, R.drawable.ic_ult_monkey_king, listOf(120, 110, 100)),
//    HeroInfo("Morphling", R.drawable.ic_morphling, R.drawable.ic_ult_morphling, listOf(130, 120, 110)),
//    HeroInfo("Naga Siren", R.drawable.ic_naga_siren, R.drawable.ic_ult_naga_siren, listOf(150, 130, 110)),
//    HeroInfo("Nature's Prophet", R.drawable.ic_natures_prophet, R.drawable.ic_ult_natures_prophet, listOf(160, 140, 120)),
//    HeroInfo("Necrophos", R.drawable.ic_necrophos, R.drawable.ic_ult_necrophos, listOf(120, 100, 90)),
//    HeroInfo("Night Stalker", R.drawable.ic_night_stalker, R.drawable.ic_ult_night_stalker, listOf(120, 100, 80)),
//    HeroInfo("Nyx Assassin", R.drawable.ic_nyx_assassin, R.drawable.ic_ult_nyx_assassin, listOf(110, 100, 90)),
//    HeroInfo("Ogre Magi", R.drawable.ic_ogre_magi, R.drawable.ic_ult_ogre_magi, listOf(100, 90, 80)),
//    HeroInfo("Omniknight", R.drawable.ic_omniknight, R.drawable.ic_ult_omniknight, listOf(160, 140, 120)),
//    HeroInfo("Oracle", R.drawable.ic_oracle, R.drawable.ic_ult_oracle, listOf(100, 90, 80)),
//    HeroInfo("Outworld Devourer", R.drawable.ic_outworld_devourer, R.drawable.ic_ult_outworld_devourer, listOf(120, 110, 100)),
//    HeroInfo("Phantom Assassin", R.drawable.ic_phantom_assassin, R.drawable.ic_ult_phantom_assassin, listOf(120, 100, 90)),
//    HeroInfo("Phantom Lancer", R.drawable.ic_phantom_lancer, R.drawable.ic_ult_phantom_lancer, listOf(130, 110, 90)),
//    HeroInfo("Phoenix", R.drawable.ic_phoenix, R.drawable.ic_ult_phoenix, listOf(200, 175, 150)),
//    HeroInfo("Puck", R.drawable.ic_puck, R.drawable.ic_ult_puck, listOf(70, 60, 50)),
//    HeroInfo("Pudge", R.drawable.ic_pudge, R.drawable.ic_ult_pudge, listOf(300, 270, 240)),
//    HeroInfo("Pugna", R.drawable.ic_pugna, R.drawable.ic_ult_pugna, listOf(140, 120, 100)),
//    HeroInfo("Queen of Pain", R.drawable.ic_queen_of_pain, R.drawable.ic_ult_queen_of_pain, listOf(100, 90, 80)),
//    HeroInfo("Razor", R.drawable.ic_razor, R.drawable.ic_ult_razor, listOf(90, 80, 70)),
//    HeroInfo("Riki", R.drawable.ic_riki, R.drawable.ic_ult_riki, listOf(90, 80, 70)),
//    HeroInfo("Rubick", R.drawable.ic_rubick, R.drawable.ic_ult_rubick, listOf(120, 100, 90)),
//    HeroInfo("Sand King", R.drawable.ic_sand_king, R.drawable.ic_ult_sand_king, listOf(80, 70, 60)),
//    HeroInfo("Shadow Demon", R.drawable.ic_shadow_demon, R.drawable.ic_ult_shadow_demon, listOf(120, 100, 90)),
//    HeroInfo("Shadow Fiend", R.drawable.ic_shadow_fiend, R.drawable.ic_ult_shadow_fiend, listOf(140, 120, 100)),
//    HeroInfo("Shadow Shaman", R.drawable.ic_shadow_shaman, R.drawable.ic_ult_shadow_shaman, listOf(150, 130, 110)),
//    HeroInfo("Silencer", R.drawable.ic_silencer, R.drawable.ic_ult_silencer, listOf(100, 90, 80)),
//    HeroInfo("Skywrath Mage", R.drawable.ic_skywrath_mage, R.drawable.ic_ult_skywrath_mage, listOf(150, 130, 110)),
//    HeroInfo("Slardar", R.drawable.ic_slardar, R.drawable.ic_ult_slardar, listOf(110, 100, 90)),
//    HeroInfo("Slark", R.drawable.ic_slark, R.drawable.ic_ult_slark, listOf(120, 110, 100)),
//    HeroInfo("Snapfire", R.drawable.ic_snapfire, R.drawable.ic_ult_snapfire, listOf(110, 100, 90)),
//    HeroInfo("Spectre", R.drawable.ic_spectre, R.drawable.ic_ult_spectre, listOf(150, 130, 110)),
//    HeroInfo("Spirit Breaker", R.drawable.ic_spirit_breaker, R.drawable.ic_ult_spirit_breaker, listOf(90, 80, 70)),
//    HeroInfo("Storm Spirit", R.drawable.ic_storm_spirit, R.drawable.ic_ult_storm_spirit, listOf(120, 100, 80)),
//    HeroInfo("Sven", R.drawable.ic_sven, R.drawable.ic_ult_sven, listOf(100, 85, 70)),
//    HeroInfo("Techies", R.drawable.ic_techies, R.drawable.ic_ult_techies, listOf(150, 130, 110)),
//    HeroInfo("Templar Assassin", R.drawable.ic_templar_assassin, R.drawable.ic_ult_templar_assassin, listOf(120, 110, 100)),
//    HeroInfo("Terrorblade", R.drawable.ic_terrorblade, R.drawable.ic_ult_terrorblade, listOf(120, 100, 80)),
//    HeroInfo("Tidehunter", R.drawable.ic_tidehunter, R.drawable.ic_ult_tidehunter, listOf(150, 130, 110)),
//    HeroInfo("Timbersaw", R.drawable.ic_timbersaw, R.drawable.ic_ult_timbersaw, listOf(90, 80, 70)),
//    HeroInfo("Tinker", R.drawable.ic_tinker, R.drawable.ic_ult_tinker, listOf(100, 90, 80)),
//    HeroInfo("Tiny", R.drawable.ic_tiny, R.drawable.ic_ult_tiny, listOf(100, 90, 80)),
//    HeroInfo("Treant Protector", R.drawable.ic_treant_protector, R.drawable.ic_ult_treant_protector, listOf(140, 120, 100)),
//    HeroInfo("Troll Warlord", R.drawable.ic_troll_warlord, R.drawable.ic_ult_troll_warlord, listOf(110, 100, 90)),
//    HeroInfo("Tusk", R.drawable.ic_tusk, R.drawable.ic_ult_tusk, listOf(100, 90, 80)),
//    HeroInfo("Underlord", R.drawable.ic_underlord, R.drawable.ic_ult_underlord, listOf(150, 130, 110)),
//    HeroInfo("Undying", R.drawable.ic_undying, R.drawable.ic_ult_undying, listOf(120, 100, 90)),
//    HeroInfo("Ursa", R.drawable.ic_ursa, R.drawable.ic_ult_ursa, listOf(90, 80, 70)),
//    HeroInfo("Vengeful Spirit", R.drawable.ic_vengeful_spirit, R.drawable.ic_ult_vengeful_spirit, listOf(120, 110, 100)),
//    HeroInfo("Venomancer", R.drawable.ic_venomancer, R.drawable.ic_ult_venomancer, listOf(120, 100, 80)),
//    HeroInfo("Viper", R.drawable.ic_viper, R.drawable.ic_ult_viper, listOf(120, 100, 80)),
//    HeroInfo("Visage", R.drawable.ic_visage, R.drawable.ic_ult_visage, listOf(150, 130, 110)),
//    HeroInfo("Void Spirit", R.drawable.ic_void_spirit, R.drawable.ic_ult_void_spirit, listOf(120, 100, 90)),
//    HeroInfo("Warlock", R.drawable.ic_warlock, R.drawable.ic_ult_warlock, listOf(150, 130, 110)),
//    HeroInfo("Weaver", R.drawable.ic_weaver, R.drawable.ic_ult_weaver, listOf(90, 80, 70)),
//    HeroInfo("Windranger", R.drawable.ic_windranger, R.drawable.ic_ult_windranger, listOf(150, 130, 110)),
//    HeroInfo("Winter Wyvern", R.drawable.ic_winter_wyvern, R.drawable.ic_ult_winter_wyvern, listOf(150, 130, 110)),
//    HeroInfo("Witch Doctor", R.drawable.ic_witch_doctor, R.drawable.ic_ult_witch_doctor, listOf(150, 130, 110)),
//    HeroInfo("Wraith King", R.drawable.ic_wraith_king, R.drawable.ic_ult_wraith_king, listOf(160, 140, 120)),
//    HeroInfo("Zeus", R.drawable.ic_zeus, R.drawable.ic_ult_zeus, listOf(120, 100, 90)),

)
